### ISSUE TITLE
Incompatible with Rails 6.1

### ISSUE THREAD

**Issue by andreaslillebo** [ParamagicDev/snowpacker#28]
When trying to install this gem from `master` with rails 6.1, I get the following error:
```
  In Gemfile:
    rails (~> 6.1.1) x86_64-linux was resolved to 6.1.1, which depends on
      railties (= 6.1.1) was resolved to 6.1.1, which depends on
        thor (~> 1.0)

    snowpacker x86_64-linux was resolved to 0.0.4.alpha1, which depends on
      thor (~> 0.20)
```

Updating `thor` to version `1.x` would likely fix this issue.

### Steps to reproduce:
1) Run `rails new` to create a new rails app
2) Add `snowpacker` to the gemfile (`gem 'snowpacker', git: 'https://github.com/ParamagicDev/snowpacker.git'`)
3) Run `bundle install`

**Comment by ParamagicDev** [comment]
Fixed with #29
